www/DACK_1112123_1112179_1112180/Controllers/ShopController.cs
using ClassLibrary.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DACK_1112123_1112179_1112180.Controllers
{
    public class ShopController : Controller
    {
        // Hiển thị danh sách đơn hàng

        giay_vipEntities db = new giay_vipEntities();
        public ActionResult Index()
        {
            return View(db.Bill_Customer);
        }

        #region Create Order
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create([Bind(Exclude = "OrderID")]Bill_Customer model)
        {
            var CartList = (List<CartVM>)Session["Cart"];
            var OrdetailsList = new BillDetail();
            
            
            model.state = 0;
            var total = CartList.Sum(m => m.Product.Price * m.Quantity);
            model.totalmoney = total.ToString();
            model.idate = DateTime.Now;
            model.xdate = DateTime.Now;
            
            // thêm danh sách OrderDetails
            
            // Thêm bảng Order
            db.Bill_Customer.Add(model);
            db.SaveChanges();
            foreach (var pro in CartList)
            {
                OrdetailsList.proid = pro.Quantity;
                db.BillDetails.Add(OrdetailsList);
                db.SaveChanges();
            }
            OrdetailsList.bilid = model.billid;
            UpdateModel(OrdetailsList);
            Session["Cart"] = null;
            return RedirectToAction("CreateSuccess");
        }
        public ActionResult CreateSuccess()
        {
            return View();
        }
        #endregion

        #region Details Order
        public ActionResult Details(int id)
        {
            return View(db.Bill_Customer.Find(id));
        }
        #endregion
        #region Delete Order
        [HttpPost]
        public ActionResult Delete(int id)
        {
            var _Order = db.Bill_Customer.Find(id);
            _Order.BillDetails.ToList().ForEach(m => db.BillDetails.Remove(m));
            db.Bill_Customer.Remove(_Order);
            db.SaveChanges();
            return new EmptyResult();
        }
        #endregion

        #region ShoppingCart
        public ActionResult ShowCart()
        {
            return View();
        }
        public ActionResult AddToCart(int id)
        {
            var _Product = db.Products.Find(id);
            var CartList = new List<CartVM>();
            if (Session["Cart"] != null)
            {
                CartList = (List<CartVM>)Session["Cart"];
                var OldCart = CartList.Find(m => m.Product.Id == id);
                if (OldCart != null)
                {
                    var NewCart = new CartVM { Product = _Product, Quantity = OldCart.Quantity + 1 };
                    CartList.Remove(OldCart);
                    CartList.Add(NewCart);
                }
                else
                {
                    CartList.Add(new CartVM { Product = _Product, Quantity = 1 });
                }
            }
            else
            {
                CartList.Add(new CartVM { Product = _Product, Quantity = 1 });
            }
            Session["Cart"] = CartList;
            return RedirectToAction("ShowCart");
        }
        public ActionResult RemoveCart(int id)
        {
            var CartList = (List<CartVM>)Session["Cart"];
            var _Cart = CartList.SingleOrDefault(m => m.Product.Id == id);
            CartList.Remove(_Cart);
            Session["Cart"] = CartList;
            return new EmptyResult();
        }
        #endregion

    }
}

www/DACK_1112123_1112179_1112180/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>

www/DACK_1112123_1112179_1112180/Views/Shared/_LayoutMainPage.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/StyleMainPage.css" rel="stylesheet" />
    
    <script src="~/Lib/js/jquery-1.11.0.min.js"></script>
	<script src="~/Lib/js/lightbox.min.js"></script>
    <link href="~/Lib/css/lightbox.css" rel="stylesheet" />
    <link href="~/Content/BackToTop.css" rel="stylesheet" /> 
    <script src="~/Scripts/simplegallery.js"></script>
    <script src="~/Scripts/backtotop.js"></script>
    <link href="~/Content/ddlevelsmenu-topbar.css" rel="stylesheet" />
    <link href="~/Content/ddlevelsmenu-base.css" rel="stylesheet" />
    <script src="~/Scripts/ddlevelsmenu.js"></script>
    <link href="~/Content/searchbox.css" rel="stylesheet" />
</head>

<body style="background: #a1a0a0">
    <div>    
        <div class="head">        
            <div class="head-detail">
                <p style="color :#fff; font-weight:bold; font-size: 20px">
                    <img src="~/Content/images/logo-top.png"/>
                </p>
            </div>

            <div class="head-detail-center">
                <div class ="menu-item">
                   <a>@Html.ActionLink("TRANG CHỦ  ", "Index", "MainPage")</a> 
                </div>
              
            <div id="account" class="menu-item">
                    <ul><li><a href="@Url.Action("ProductCategory", "MainPage")" rel="subaccount">SẢN PHẨM</a></li></ul>
                </div>
                <script type="text/javascript">
                    ddlevelsmenu.setup("account", "topbar")
            </script>
                <ul id="subaccount" class="ddsubmenustyle">
                <li><a href="@Url.Action("Product/98", "MainPage")">CHUCK TAYLOR</a></li>
                <li><a href="@Url.Action("Product/99", "MainPage")">CONS</a></li>
                <li><a href="@Url.Action("Product/100", "MainPage")">JACK PURCELL</a></li>
                <li><a href="@Url.Action("Product/100", "MainPage")">JACK PURCELL</a></li>
                <li><a href="@Url.Action("Product/100", "MainPage")">JACK PURCELL</a></li>
            </ul>
                
                <div class ="menu-item" style="margin-left:20px">
                    <a>@Html.ActionLink("LIÊN HỆ  ", "Index", "MainPage")</a> 
                </div>
                <div class="search-area" style="margin-top:10px">

                    @using (Html.BeginForm("Tim", "MainPage"))
                    {
                        <form  id="search">
                            <input type=text name=search size ="40" placeholder="Search..."  />
                        </form>
                    } 
                </div> 
            </div>
            
            <div class="head-detail">               
                   
                    @if (ClassLibrary.Models.Account.name.ToString() == "" )
                    {
                        <div class ="menu-items" style="font-size:14px">
                            <a>@Html.ActionLink("TÀI KHOẢN", "Login", "MainPage")</a>
                         </div>
                    } else if (ClassLibrary.Models.Account.name.ToString() != "" && ClassLibrary.Models.Account.admin == true)
                    { 
                        <div class ="menu-items" style="font-size:14px">
                         @Html.ActionLink("Chào "+ @ClassLibrary.Models.Account.name.ToString(), "EditAccount", "MainPage", new { id = ClassLibrary.Models.Account.id }, null)
                            
                            </div>
                        <div class ="menu-items" style="font-size:14px">
                        <a href="/MainPage/AdminManager"> Quản Lý</a>
                            </div>
                        <div class ="menu-items" style="font-size:14px">
                        <a href="/MainPage/Logout"> Thoát</a>
                            </div>
                    }else if (ClassLibrary.Models.Account.name.ToString() != "" && ClassLibrary.Models.Account.admin == false)
                    {
                        <div class ="menu-items" style="font-size:14px">
                        @Html.ActionLink("Chào "+ @ClassLibrary.Models.Account.name.ToString(), "EditAccount", "MainPage", new { id = ClassLibrary.Models.Account.id }, null)    
                            </div>
                        <div class ="menu-items" style="font-size:14px">                  
                        <a href="/MainPage/Logout"> Thoát</a>
                         </div>
                    }
                    
              

                <div class ="menu-items" >
                   <a style="font-size:10px">@Html.ActionLink("Giỏ Hàng", "ShowCart", "Shop")</a>                     
                </div>
               
               
            </div>

           
             
            @*<div id="sse1">
                <div id="sses1">
                    <ul>
                        <li><a href="?menu=1&skin=2&p=Javascript-Menus">@Html.ActionLink("Trang Chủ  ", "Index", "MainPage")</a></li>
                        <li><a href="?menu=1&skin=2&p=Javascript-Menus">@Html.ActionLink("Sản Phẩm ", "ProductCategory", "MainPage")</a></li>

                    </ul>
                </div>
                
                <ul>
                    @if (ClassLibrary.Models.Account.name.ToString() == "" )
                    {
                        <li><a>@Html.ActionLink("Tài Khoản", "Login", "MainPage")</a></li>
                    }
                    else if (ClassLibrary.Models.Account.name.ToString() != "" && ClassLibrary.Models.Account.admin == false)
                    {
                        <li><a> Welcome @Session["LogedUserFullname"].ToString()</a></li>                        
                        <li><a href="/MainPage/Logout"> Thoát</a></li>
                    }
                    else if (ClassLibrary.Models.Account.name.ToString() != "" && ClassLibrary.Models.Account.admin == true)
                    { 
                        <li><a> Welcome @Session["LogedUserFullname"].ToString()</a></li>
                        <li><a href="/MainPage/AdminManager"> Quản Lý</a></li>
                        <li><a href="/MainPage/Logout"> Thoát</a></li>
                    }
                    
                    <li><a href="?menu=1&skin=2&p=Javascript-Menus">Giỏ Hàng</a></li>
                </ul>

            </div>*@

        </div>
       
        
        <div>
            @RenderBody()
        </div>
        
        <div class="bottom">
            <div class="bottom-detail">
                <p style="color :#fff; font-weight:bold; font-size: 20px">
                    Giới thiệu!
                </p>
                <p style="color: #fff">
                    "Chúng tôi khác biệt...!" - Sau 5 năm thành lập đến nay hệ thống cửa hàng YaMe đã ngày càng phát triển và hoàn thiện hơn so với những năm về trước, và đáp ứng nhu cầu mua sắm của các bạn trẻ. 
                </p>

                <p style="color: #0094ff; font-weight:bold; text-align:center">
                    Đặt hàng, thu tiền tận nơi toàn quốc:
                    <br />
                        01662 036 464
                    <br />
                    (08:00 – 20:00, Chủ nhật nghỉ )
                </p>
            </div>

            <div class ="bottom-detail" style="padding: 30px; width : 450px">
                <p style="color :#fff; font-weight:bold; font-size: 16px">
                    521/96A - CMT8 - Phường 13 - Quận 10 - TP.HCM 
                </p>
                <p style="color :#fff; font-weight:bold; font-size: 16px">
                    206E - Lê Văn Sĩ - Phường 10 - Quận Phú Nhuận - TP. HCM
                </p>
                <p style="color :#fff; font-weight:bold; font-size: 16px">
                    336 - Võ Văn Ngân - Quận Thủ Đức - TP.HCM 
                </p>

            </div>

             <div class ="bottom-detail">
                 <p style="color:#0094ff; font-family:'Times New Roman'; font-weight:bold; font-size: 20px">
                     Theo dõi chúng tôi trên: 
                 </p>
                  <a href="https://www.facebook.com/leducmanh.it"; target="_blank">                     
                        <img src="~/Content/images/icon-facebook.png"; style="width: 100px; height: 100px; margin: 15px 10px auto;" />
                  </a>    
                 <a href="https://plus.google.com/u/0/+L%C3%AA%C4%90%E1%BB%A9cM%E1%BA%A1nh_AT%C5%A9n/posts"; target="_blank">                     
                        <img src="~/Content/images/icon-google.png"; style="width: 100px; height: 100px; margin: 15px 10px auto;" />
                  </a>            
            </div>
        </div>

        <div >
            <div id="pagewrap">
                <div style="height: 0px;"></div>
                <p id="back-top">
                    <a href="#top"><span></span>Back to Top</a>
                </p>
            </div>
        </div>
    </div> 
        @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>